# Build MEXlibCZI for Windows-x64 and Linux-x64

trigger:
- master

jobs:
- job: Windowsx64
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'mlfiles2.zip'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)/mlfiles2.zip'
      destinationFolder: 'matlabheaders'
      cleanDestinationFolder: true    
  - task: CMake@1
    inputs:
      workingDirectory: $(Build.SourcesDirectory)/build
      cmakeArgs: '.. -A x64 -DCMAKE_BUILD_TYPE=Release -DMEXLIBCZI_HEADERS=$(Build.SourcesDirectory)\matlabheaders\include -DMEXLIBCZI_LIBS=$(Build.SourcesDirectory)\matlabheaders\lib'
  - task: CmdLine@2
    inputs:
      script: 'cmake --build  .\build --config Release'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.SourcesDirectory)/build/MEXlibCZI/Release/MEXlibCZI.mexw64
      artifactName: MEXlibCZIWinx64
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
- job: Linuxx64
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'mlfiles2.zip'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)/mlfiles2.zip'
      destinationFolder: 'matlabheaders'
      cleanDestinationFolder: true    
  - task: CMake@1
    inputs:
      cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DMEXLIBCZI_HEADERS=$(Build.SourcesDirectory)/matlabheaders/include -DMEXLIBCZI_LIBS=$(Build.SourcesDirectory)/matlabheaders/lib'
  - script: |
      cmake --build  ./build --config Release
    displayName: 'Build Linux-x64'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.SourcesDirectory)/build/MEXlibCZI/Release/MEXlibCZI.mexa64
      artifactName: MEXlibCZILinuxx64
