# Build MEXlibCZI for Windows-x64 and Linux-x64

trigger:
- master

jobs:
- job: Windowsx64
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'mlfiles.zip'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Agent.TempDirectory)\mlfiles.zip'
      destinationFolder: 'matlabheaders'
      cleanDestinationFolder: true    
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
